### ISSUE TITLE
 /app/vendor does not exist and could not be created.

### ISSUE THREAD

**Issue by flourishing** [bitnami/bitnami-docker-laravel#89] opened 2018-08-13 07:36 UTC
I was trying to run composer install  and it reported error.

after i started laravel docker, i run
docker-compose exec myapp composer install

it reported /app/vendor does not exist and could not be created.
i have tried change mkdir app/vendor and change 777 to it . but doesn't work.
how to deal with it ?thanks

**Comment by rafariossaa** [comment] 2018-08-14 08:06
Hi,

  I have tried to reproduce this but I don't get this error.

  Could you provide a complete log? 

Thanks

Best regards,

Rafael Rios

**Comment by flourishing** [comment] 2018-08-14 14:29
`root@li408-10:~# mkdir ~/myapp && cd ~/myapp
root@li408-10:~/myapp# curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-laravel/master/docker-compose.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   556  100   556    0     0   1865      0 --:--:-- --:--:-- --:--:--  1865
root@li408-10:~/myapp# docker-compose up
Creating network "myapp_default" with the default driver
Creating myapp_mariadb_1 ... 
Creating myapp_mariadb_1 ... done
Creating myapp_myapp_1 ... 
Creating myapp_myapp_1 ... done
Attaching to myapp_mariadb_1, myapp_myapp_1
mariadb_1  | 
mariadb_1  | Welcome to the Bitnami mariadb container
myapp_1    | 
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
myapp_1    | Welcome to the Bitnami laravel container
myapp_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-laravel
myapp_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-laravel/issues
myapp_1    | Send us your feedback at containers@bitnami.com
myapp_1    | 
myapp_1    | Creating laravel application
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | 
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
myapp_1    | cp: cannot create regular file '/app/.env': Permission denied
myapp_1    | cp: cannot create regular file '/app/.env.example': Permission denied
myapp_1    | cp: cannot create regular file '/app/.gitattributes': Permission denied
myapp_1    | cp: cannot create regular file '/app/.gitignore': Permission denied
myapp_1    | cp: cannot create directory '/app/app': Permission denied
myapp_1    | cp: cannot create regular file '/app/artisan': Permission denied
myapp_1    | cp: cannot create directory '/app/bootstrap': Permission denied
myapp_1    | cp: cannot create regular file '/app/composer.json': Permission denied
myapp_1    | cp: cannot create regular file '/app/composer.lock': Permission denied
myapp_1    | cp: cannot create directory '/app/config': Permission denied
myapp_1    | cp: cannot create directory '/app/database': Permission denied
myapp_1    | cp: cannot create regular file '/app/package.json': Permission denied
myapp_1    | cp: cannot create regular file '/app/phpunit.xml': Permission denied
myapp_1    | cp: cannot create directory '/app/public': Permission denied
myapp_1    | cp: cannot create regular file '/app/readme.md': Permission denied
myapp_1    | cp: cannot create directory '/app/resources': Permission denied
myapp_1    | cp: cannot create directory '/app/routes': Permission denied
myapp_1    | cp: cannot create regular file '/app/server.php': Permission denied
myapp_1    | cp: cannot create directory '/app/storage': Permission denied
myapp_1    | cp: cannot create directory '/app/tests': Permission denied
myapp_1    | cp: cannot create directory '/app/vendor': Permission denied
myapp_1    | cp: cannot create regular file '/app/webpack.mix.js': Permission denied
myapp_myapp_1 exited with code 1
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO  ==> Cleaning data dir...
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | mariadb INFO  ==> Validating inputs...
mariadb_1  | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1  | mariadb INFO  ==> Initializing database...
mariadb_1  | mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb_1  | mariadb INFO  ==> Creating database my_database...
mariadb_1  | mariadb INFO  ==> Creating user my_user...
mariadb_1  | mariadb INFO  ==> Granting access to my_user to the database my_database...
mariadb_1  | mariadb INFO 
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO   Installation parameters for mariadb:
mariadb_1  | mariadb INFO     Root User: root
mariadb_1  | mariadb INFO     Root Password: Not set during installation
mariadb_1  | mariadb INFO     Database: my_database
mariadb_1  | mariadb INFO     Username: my_user
mariadb_1  | mariadb INFO     Password: **********
mariadb_1  | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO 
mariadb_1  | nami    INFO  mariadb successfully initialized
mariadb_1  | INFO  ==> Starting mariadb... 
mariadb_1  | INFO  ==> Starting mysqld_safe.....
mariadb_1  | 180814 14:20:42 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1  | 180814 14:20:42 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data`

**Comment by rafariossaa** [comment] 2018-08-14 15:31
Hi,

 The problem is that you are using root for creating the myapp dir, try doing all the steps under a regular user. 

```
bitnami@bitnami:~$ mkdir ~/myapp
bitnami@bitnami:~$ cd ~/myapp
bitnami@bitnami:~/myapp$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-laravel/master/docker-compose.yml 
bitnami@bitnami:~/myapp$ docker-compose up
myapp_mariadb_1 is up-to-date
Starting myapp_myapp_1 ... done
Attaching to myapp_mariadb_1, myapp_myapp_1
myapp_1    | 
myapp_1    | Welcome to the Bitnami laravel container
myapp_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-laravel
myapp_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-laravel/issues
myapp_1    | Send us your feedback at containers@bitnami.com
myapp_1    | 
myapp_1    | Creating laravel application
mariadb_1  | 
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | 
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO  ==> Cleaning data dir...
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | mariadb INFO  ==> Validating inputs...
mariadb_1  | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1  | mariadb INFO  ==> Initializing database...
mariadb_1  | mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb_1  | mariadb INFO  ==> Creating database my_database...
mariadb_1  | mariadb INFO  ==> Creating user my_user...
mariadb_1  | mariadb INFO  ==> Granting access to my_user to the database my_database...
mariadb_1  | mariadb INFO 
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO   Installation parameters for mariadb:
mariadb_1  | mariadb INFO     Root User: root
mariadb_1  | mariadb INFO     Root Password: Not set during installation
mariadb_1  | mariadb INFO     Database: my_database
mariadb_1  | mariadb INFO     Username: my_user
mariadb_1  | mariadb INFO     Password: **********
mariadb_1  | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO 
mariadb_1  | nami    INFO  mariadb successfully initialized
mariadb_1  | INFO  ==> Starting mariadb... 
mariadb_1  | INFO  ==> Starting mysqld_safe.....
mariadb_1  | 180814 15:22:20 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1  | 180814 15:22:20 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
myapp_1    | Installing/Updating Laravel dependencies (composer)
myapp_1    | Loading composer repositories with package information
myapp_1    | Updating dependencies (including require-dev)
myapp_1    | Package operations: 0 installs, 27 updates, 0 removals
myapp_1    |   - Updating vlucas/phpdotenv (v2.4.0 => v2.5.1): Downloading (100%)         
myapp_1    |   - Updating symfony/css-selector (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating symfony/polyfill-php72 (v1.8.0 => v1.9.0): Downloading (100%)         
myapp_1    |   - Updating symfony/polyfill-mbstring (v1.8.0 => v1.9.0): Downloading (100%)         
myapp_1    |   - Updating symfony/var-dumper (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating symfony/routing (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating symfony/process (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating symfony/polyfill-ctype (v1.8.0 => v1.9.0): Downloading (100%)         
myapp_1    |   - Updating symfony/http-foundation (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating symfony/event-dispatcher (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating symfony/debug (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating symfony/http-kernel (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating paragonie/random_compat (v2.0.15 => v9.99.99): Downloading (100%)         
myapp_1    |   - Updating symfony/finder (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating symfony/console (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating swiftmailer/swiftmailer (v6.0.2 => v6.1.2): Downloading (100%)         
myapp_1    |   - Updating ramsey/uuid (3.7.3 => 3.8.0): Downloading (100%)         
myapp_1    |   - Updating symfony/translation (v4.1.0 => v4.1.3): Downloading (100%)         
myapp_1    |   - Updating laravel/framework (v5.6.26 => v5.6.33): Downloading (100%)         
myapp_1    |   - Updating fzaninotto/faker (v1.7.1 => v1.8.0): Downloading (100%)         
myapp_1    |   - Updating sebastian/comparator (3.0.1 => 3.0.2): Downloading (100%)         
myapp_1    |   - Updating phpspec/prophecy (1.7.6 => 1.8.0): Downloading (100%)         
myapp_1    |   - Updating phar-io/version (1.0.1 => 2.0.1): Downloading (100%)         
myapp_1    |   - Updating phar-io/manifest (1.0.1 => 1.0.3): Downloading (100%)         
myapp_1    |   - Updating phpunit/phpunit (7.2.6 => 7.3.1): Downloading (100%)         
myapp_1    |   - Updating nikic/php-parser (v4.0.2 => v4.0.3): Downloading (100%)         
myapp_1    |   - Updating psy/psysh (v0.9.6 => v0.9.7): Downloading (100%)         
myapp_1    | Writing lock file
myapp_1    | Generating optimized autoload files
myapp_1    | > Illuminate\Foundation\ComposerScripts::postAutoloadDump
myapp_1    | > @php artisan package:discover
myapp_1    | Discovered Package: fideloper/proxy
myapp_1    | Discovered Package: laravel/tinker
myapp_1    | Discovered Package: nunomaduro/collision
myapp_1    | Package manifest generated successfully.
myapp_1    | Dependencies updated
myapp_1    | Connecting to mariadb at 172.20.0.2
myapp_1    | Configuring the database
myapp_1    | Migration table created successfully.
myapp_1    | Migrating: 2014_10_12_000000_create_users_table
myapp_1    | Migrated:  2014_10_12_000000_create_users_table
myapp_1    | Migrating: 2014_10_12_100000_create_password_resets_table
myapp_1    | Migrated:  2014_10_12_100000_create_password_resets_table
myapp_1    | Initialization finished
myapp_1    | Laravel development server started: <http://0.0.0.0:3000>

```

**Comment by flourishing** [comment] 2018-08-15 14:06
i create a regular user, it reports
jpr@li408-10:~/myapp2$ docker-compose up
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

thanks for your help

**Comment by rafariossaa** [comment] 2018-08-16 06:56
Hi,

  May be it is because the regular user you created it is not in the docker group.

  I would suggest you to review docker install [documentation](https://docs.docker.com/v17.09/engine/installation/linux/linux-postinstall/).

I proceed to close this ticket as solved. If you have any other questions, please do not hesitate to open a new thread. 

Best regards,

Rafael Rios

**Closed** 2018-08-17 09:17 UTC

**Comment by mtuchi** [comment] 2020-04-19 13:45
Am facing the same problem on my production server (see logs below 👇.
It works fine in my local machine but facing this problem on the production server
```
154 ± : docker-compose up                                                                                                                                                                                                               [49m]
Starting app_mariadb_1 ... done
Starting app_myapp_1   ... done
Attaching to app_mariadb_1, app_myapp_1
mariadb_1  | mariadb 13:42:57.66
mariadb_1  | mariadb 13:42:57.66 Welcome to the Bitnami mariadb container
mariadb_1  | mariadb 13:42:57.66 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | mariadb 13:42:57.67 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | mariadb 13:42:57.67 Send us your feedback at containers@bitnami.com
mariadb_1  | mariadb 13:42:57.67
mariadb_1  | mariadb 13:42:57.67 INFO  ==> ** Starting MariaDB setup **
mariadb_1  | mariadb 13:42:57.75 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1  | mariadb 13:42:57.76 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | mariadb 13:42:57.76 INFO  ==> Initializing mariadb database
mariadb_1  | mariadb 13:42:57.79 INFO  ==> Using persisted data
mariadb_1  | mariadb 13:42:57.80 INFO  ==> Running mysql_upgrade
mariadb_1  | mariadb 13:42:57.81 INFO  ==> Starting mariadb in background
myapp_1    |
myapp_1    | Welcome to the Bitnami laravel container
myapp_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-laravel
myapp_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-laravel/issues
myapp_1    | Send us your feedback at containers@bitnami.com
myapp_1    |
myapp_1    | Installing/Updating Laravel dependencies (composer)
mariadb_1  | mariadb 13:42:58.84 INFO  ==> Stopping mariadb
myapp_1    | Loading composer repositories with package information
myapp_1    | Installing dependencies (including require-dev) from lock file
myapp_1    | Package operations: 93 installs, 0 updates, 0 removals
myapp_1    |
myapp_1    |
myapp_1    |   [RuntimeException]
myapp_1    |   /app/vendor does not exist and could not be created.
myapp_1    |
myapp_1    |
myapp_1    | install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
myapp_1    |
app_myapp_1 exited with code 1
app_mariadb_1 exited with code 1
```

**Comment by rafariossaa** [comment] 2020-04-20 16:27
Hi @mtuchi ,
  This issue is closed, and as several releases were done since this issue was opened, do you mind to open a new issue so proper tracking of it can be done ?

Thanks forehand.
